gems:
  - jemoji
  - jekyll-paginate
title: "Left of Null"
email: leftofnull@outlook.com
description: >-
  Covering Coding, Technology, and Life.
baseurl: "/testblog"
url: "/testblog" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/assets/images/logo.png"
float_logo: true
cover: "/assets/images/programming.jpg"
name: "Alexander Kahoun"
author: "Alexander Kahoun"
author_image: "/assets/images/author.jpg"
twitter_handle: "@bit_cmdr"
github_username: bit-cmdr
google_analytics: UA-56155652-1
show_downloads: false
paginate: 5
disqus: leftofnull
social:
  - icon:	twitter
    url:	https://twitter.com/bit_cmdr
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="
  - icon:	github
    url:	https://github.com/bit-cmdr
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:
# Build settings
markdown: kramdown
theme: jekyll-theme-slate
plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
